import type { Product } from "../types";

export const CATALOG: Record<string, Product> = {
  "puerto-rico-paradise": {
    id: "puerto-rico-paradise",
    name: "Puerto Rico Paradise",
    destination: "Puerto Rico",
    mood: "Tropical Warmth",
    scents: ["Creamy Coconut", "Pineapple", "Vanilla Orchid"],
    price: 22.0,
    inStock: true,
    tag: "NEW",
    image: "/aromamor-candles/Puerto Rico Paradise.png",
  },
  "parisian-cafe": {
    id: "parisian-cafe",
    name: "Parisian Café",
    destination: "Paris, France",
    mood: "Cozy & Romantic",
    scents: ["Fresh Espresso", "Warm Vanilla", "Brown Sugar"],
    price: 22.0,
    inStock: true,
    tag: "BESTSELLER",
    image: "/aromamor-candles/Parisian Cafe.png",
  },
  "santorini-breeze": {
    id: "santorini-breeze",
    name: "Santorini Breeze",
    destination: "Santorini, Greece",
    mood: "Coastal Escape",
    scents: ["Sea Salt", "White Citrus", "Driftwood"],
    price: 22.0,
    inStock: false,
    tag: "LIMITED",
    image: "/aromamor-candles/Santorini Breeze.png",
  },
  "first-class-lounge": {
    id: "first-class-lounge",
    name: "First Class Lounge",
    destination: "Luxury Airport Lounge",
    mood: "Sophisticated & Calm",
    scents: ["Amber", "Cashmere", "Soft Vanilla"],
    price: 24.0,
    inStock: true,
    tag: "SIGNATURE",
    image: "/aromamor-candles/First Class Lounge.png",
  },
  "graceful-journey": {
    id: "graceful-journey",
    name: "Graceful Journey",
    destination: "A Season of Faith",
    mood: "Peaceful & Reflective",
    scents: ["Lavender", "White Tea", "Light Cedar"],
    price: 22.0,
    inStock: true,
    tag: "CALM",
    image: "/aromamor-candles/Graceful Journey.png",
  },
  "amalfi-morning": {
    id: "amalfi-morning",
    name: "Amalfi Morning",
    destination: "Amalfi Coast, Italy",
    mood: "Charmingly Vibrant",
    scents: ["Lemon Zest", "Sugar", "Light Cream"],
    price: 22.0,
    inStock: true,
    tag: "FRESH",
    image: "/aromamor-candles/Amalfi Morning.png",
  },
};
